export const GET_ACCOMODATION = "GET_ACCOMODATION";
export const ADD_ACCOMODATION = "ADD_ACCOMODATION";
export const UPDATE_ACCOMODATION = "UPDATE_ACCOMODATION";
export const DELETE_ACCOMODATION = "DELETE_ACCOMODATION";
export const GET_TOP_ACCOMODATION = "GET_TOP_ACCOMODATION";
export const GET_ACCOMODATION_GROUPED = "GET_ACCOMODATION_GROUPED";
export const GET_SINGLE_ACCOMODATION = "GET_SINGLE_ACCOMODATION";

// gym
export const UPDATE_GYM = "UPDATE_GYM";
export const UPDATE_POOL = "UPDATE_POOL";
export const UPDATE_HALL = "UPDATE_HALL";
export const UPDATE_RESTAURANT = "UPDATE_RESTAURANT";