export const GET_CLUB_PRODUCTS = "GET_CLUB_PRODUCTS";
export const ADD_CLUB_PRODUCTS = "ADD_CLUB_PRODUCTS";
export const UPDATE_CLUB_PRODUCTS = "UPDATE_CLUB_PRODUCTS";
export const DELETE_CLUB_PRODUCTS = "DELETE_CLUB_PRODUCTS";