export const GET_COFFEE_PRODUCTS = "GET_COFFEE_PRODUCTS";
export const ADD_COFFEE_PRODUCTS = "ADD_COFFEE_PRODUCTS";
export const UPDATE_COFFEE_PRODUCTS = "UPDATE_COFFEE_PRODUCTS";
export const DELETE_COFFEE_PRODUCTS = "DELETE_COFFEE_PRODUCTS";