export const GET_HOTEL_PRODUCTS = "GET_HOTEL_PRODUCTS";
export const GET_GROUPEDHOTEL_PRODUCTS = "GET_GROUPEDHOTEL_PRODUCTS";
export const ADD_HOTEL_PRODUCTS = "ADD_HOTEL_PRODUCTS";
export const UPDATE_HOTEL_PRODUCTS = "UPDATE_HOTEL_PRODUCTS";
export const DELETE_HOTEL_PRODUCTS = "DELETE_HOTEL_PRODUCTS";