export const GET_RESTAURANTS = "GET_RESTAURANTS";
export const ADD_RESTAURANTS = "ADD_RESTAURANTS";
export const UPDATE_RESTAURANTS = "UPDATE_RESTAURANTS";
export const DELETE_RESTAURANTS = "DELETE_RESTAURANTS";