export const GET_RESTAURANT_PRODUCTS = "GET_RESTAURANT_PRODUCTS";
export const ADD_RESTAURANT_PRODUCTS = "ADD_RESTAURANT_PRODUCTS";
export const UPDATE_RESTAURANT_PRODUCTS = "UPDATE_RESTAURANT_PRODUCTS";
export const DELETE_RESTAURANT_PRODUCTS = "DELETE_RESTAURANT_PRODUCTS";